### ISSUE TITLE
Add tripal content

### ISSUE THREAD

**Issue by mpoelchau** [NAL-i5K/Organism_Onboarding#96]
This workflow will create Tripal organism and analysis pages, and as much information to these pages as we can, following our guidelines: https://gitlab.com/i5k_Workspace/workspace_roadmap/-/wikis/Adding-an-organism-CWL-update#5-set-up-tripal-pages. Note that we can't add all the information that we currently do via the command line - but this will give us a start. 

- Create workflow to add an organism page using `tripaille organism add_organism` (type `-h` to get the help page); 
- Create workflow to add the assembly analysis page using `tripaille analysis add_analysis` ; 
- Create workflow to add  the annotation analysis page using `tripaille analysis add_analysis` (and maybe `tripaille analysis get_analysis` to get the assembly node URL...)

**Comment by childers** [comment]
Here is the error when running the command via CWL.  it works when you nter the same command in the terminal.

@HsiuKangHuang can you specify character encoding in CWL? I think there might be an encoding issue when CWL is used to make the command


```Traceback (most recent call last):
  File "/home/hsiukang.huang/tripal-test/bin/tripaille", line 9, in <module>
    load_entry_point('tripal==3.2.1', 'console_scripts', 'tripaille')()
  File "/home/hsiukang.huang/tripal-test/lib64/python3.5/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/hsiukang.huang/tripal-test/lib64/python3.5/site-packages/click/core.py", line 760, in main
    _verify_python3_env()
  File "/home/hsiukang.huang/tripal-test/lib64/python3.5/site-packages/click/_unicodefun.py", line 130, in _verify_python3_env
    " mitigation steps.{}".format(extra)
RuntimeError: Click will abort further execution because Python 3 was configured to use ASCII as encoding for the environment. Consult https://click.palletsprojects.com/python3/ for mitigation steps.
```

**Comment by mpoelchau** [comment]
We tried installing python3.8 to see if that would fix the above error. This resulted in SSL errors when trying to use pip in the python3.8 virtual environment:

```
WARNING: pip is configured with locations that require TLS/SSL, however the ssl module in Python is not available.
Collecting ssl
  WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/ssl/
  WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/ssl/
  WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/ssl/
  WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/ssl/
  WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/ssl/
  Could not fetch URL https://pypi.org/simple/ssl/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/ssl/ (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available.")) - skipping
  ERROR: Could not find a version that satisfies the requirement ssl (from versions: none)
ERROR: No matching distribution found for ssl
WARNING: pip is configured with locations that require TLS/SSL, however the ssl module in Python is not available.
Could not fetch URL https://pypi.org/simple/pip/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/pip/ (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available.")) - skipping
```

Some googling suggested updating the openssl version. I updated openssl based on this documentation, as suggested by @childers:   https://linuxscriptshub.com/update-openssl-1-1-0-centos-6-9-7-0/

Update was successful as far as I can tell. However, it didn't solve the pip problem:

```
$ /app/data/hsiukang/py38/Python-3.8.2/python -V
Python 3.8.2
$ /app/data/hsiukang/py38/Python-3.8.2/python -m venv venv-python3.8
$ source venv-python3.8/bin/activate
$ pip list
Package    Version
---------- -------
pip        19.2.3 
setuptools 41.2.0 
WARNING: pip is configured with locations that require TLS/SSL, however the ssl module in Python is not available.
Could not fetch URL https://pypi.org/simple/pip/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/pip/ (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available.")) - skipping
$ openssl version
OpenSSL 1.1.0f  25 May 2017
```

@childers I'm stumped. Any ideas on how to proceed?
